name: Validation

on:
  push:
    branches: [ main ]

permissions:
  # Required for reading the repo
  contents: read
  # Used for the publication of test results
  checks: write

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17-jdk-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: ./gradlew test --parallel
      - name: Publish test report
        uses: mikepenz/action-junit-report@v4.0.3
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
